### ISSUE TITLE
feat: Add Specific validation from smart orders by delegating to BaseConditionalOrder instances

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/tenderly-watch-tower#7]
Add Specific validation from smart orders by delegating to BaseConditionalOrder instances.

Make a new method in `BaseConditionalOrder` that would allow to delegate the validation to BaseConditionalOrder instances.

The validations should tell the watch-tower as a result one of the following:
- Validations is OK
- Error validating: for unhandled errors? (alternative, we could throw)
- It's not yet time to place an order
- This order will never generate a discrete order (i.e. expired TWAP)

**Comment by anxolin** [comment]
This PR in the SDK will implement the core logic and abstractions for this https://github.com/cowprotocol/cow-sdk/pull/149

**Comment by anxolin** [comment]
This PR in the SDK will implement the core logic and abstractions for this https://github.com/cowprotocol/cow-sdk/pull/149

**Comment by mfw78** [comment]
@anxolin From the looks of this with the current status of `main`, this has been implemented and can be closed?
