### ISSUE TITLE
feat: Allow specific order implementations to signal the next checkTime

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/tenderly-watch-tower#8]
WatchTower default behaviour will check, for every single block, if its time to place an order.

This, doesn't scale well, because each check will require some RPC calls, and validations, and there's situations where this can be avoided. 

For example, in TWAP it is deterministic what is the next moment in time where we will be able to place the next discreate order.

This PR is about signaling the watch tower what is the next checkTime, and waiting patiently until the time is right.

**Comment by mfw78** [comment]
In order to formalise this, I think the `poll` on the Conditional Order, should return when to poll the conditional order again, based on either:

1. Timestamp.
2. Block Number.

This would keep it relatively order agnostic.

**Comment by anxolin** [comment]
This PR in the SDK will implement the core logic and abstractions for this https://github.com/cowprotocol/cow-sdk/pull/149

**Comment by anxolin** [comment]
This PR now do the polling, and set up all the structure so this happens:
https://github.com/cowprotocol/tenderly-watch-tower/pull/16

Left here placeholder to handle it:
https://github.com/cowprotocol/tenderly-watch-tower/pull/16/files#diff-8e2dc90f4a6ebdf01f8603707f37f7794972fdf1827102bfce89497804f72837R100
